### ISSUE TITLE
Bug: Undefined behavior when running generate on a file that doesn't have code

### ISSUE THREAD

**Issue by Mounayer** [cleobnvntra/rm-generator#7]
# Description
When I ran `rm-generator generate` on a file that does not contain source code, for example, on a file that contains:

```
One upon a time, there was a boy named Romeo. Then, Romeo met Juliet!
```

The `rm-generator` still generated a readme file for it, discussing Shakespearean tragedies, going deeper into the story, etc... This should not be happening. Instead, the `rm-generator` should throw an error when it attempts to process a file that does not contain source code!

![image](https://github.com/user-attachments/assets/6ee1d6eb-e22d-484a-8b39-f3a687adb3b6)

## Reproducing The Issue

- Run `rm-generator generate none_source_code_file` or substitute `none_source_code_file` with any file name of a file that doesn't have source code in it, in your directory.
- Verify that a README.md file has been generated discussing/analyzing the content of your file -- even though it is not source code.

## Fix Suggestion

- Further enhance the prompts given to the LLM using these [Prompt Engineer Tips](https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/15-tips-to-become-a-better-prompt-engineer-for-generative-ai/ba-p/3882935), particularly focusing on emphasizing the importance of certain prompts, and reiterating the most crucial prompts, i.e.:

```typescript
      const prompt = `
      Important Note: IF THE FILE CONTENT GIVEN IS NOT SOURCE CODE, REPLY WITH 'Unable To Process'. 

      Please generate a README.md file explaining the contents of the following file.
      The README should have a title, description, and code snippets with explanations.
      The code snippet should be pieces of code from the source code file. Not the entire code.
      The title should be # tag, subheadings should be ## tags, and code snippets should be in a code block.
      Do not use "Title" as the title header. Just use directly the title for the documentation as the title header.
      Code snippets should be in a code block using the triple backticks.
      The generated README must be according to documentation stanrdards.
      This README will be used to document the source code file. Generate the README as if you are documenting the source code for a project.

      Important Note: IF THE FILE CONTENT GIVEN IS NOT SOURCE CODE, REPLY WITH 'Unable To Process'.`;
```

Then handle the `Unable To Process` message in your code, perhaps print to the screen that `README.md` generation has halted because the content provided was not code.

**Comment by cleobnvntra** [comment]
As someone completely new with prompt engineering, I never thought something as simple as this could completely break my prompt! Thank you for catching this and providing some tips!

I have improved my prompt and should now properly handle non-code related files or files that contain no code at all.

Closed this issue with PR: #10
