### ISSUE TITLE
Issue: Generated readme replaces repo's readme file

### ISSUE THREAD

**Issue by Mounayer** [cleobnvntra/rm-generator#8]
# Description
When I ran the `rm-generator generate main.cpp` command, the generated `README.md` file replaced the project's `README.md` file. 
Perhaps there should be a functionality that modifies the name of the generated file to something like `FILENAME_README.md` instead of just `README.md`.

![image](https://github.com/user-attachments/assets/c52e99a2-f833-4fed-86bc-8c45230c3331)

## Reproducing The Issue

- Create any source code file in the current repository, i.e. `main.cpp`.
- Run `rm-generator generate main.cpp`
- Verify that the repository's `README.md` file has been replaced with a new `README.md` file explaining the `main.cpp` file that was processed

## Fix Suggestion

For now, maybe simply updating the name of the file generated in `index.js` from:

```typescript
const outputPath = path.join(fileDir, "README.md");
```
to
```typescript
const outputPath = path.join(fileDir, `${file}_README.md`);
```

**Comment by cleobnvntra** [comment]
Thank you for catching this.

I wrote the code with the assumption that the user will be passing files from a different directory when using the tool.
This also provided me an idea for a possible feature in the future!

Closed this issue with PR: #9
